### ISSUE TITLE
Default player's money always zero.

### ISSUE THREAD

**Issue by geekjam** [notabadminer/UniversalCoinsVaultPlugin#1]
Other player is work

**Comment by geekjam** [comment]
Sorry about that, when i check with Chinese character user names will not working

**Comment by notabadminer** [comment]
Is the error from commands or interacting with a plugins stuff like a signshop sign?

**Comment by geekjam** [comment]
When use Chinese character user names /balance is always $0,English characters is work

**Comment by notabadminer** [comment]
OK. I will see if I can fix it tomorrow.

**Comment by notabadminer** [comment]
I'm not sure why it's not working for you. The commands are part of the Forge mod, not this plugin. The commands all use the player UUID so the player name should not be an issue. I tried using a Chinese name and switching to Chinese lang from the option menu. I didn't find anything wrong.

Can you PM me the usernamecache.json and universalcoins.dat files through http://www.minecraftforum.net? With those files, I can see if the username is mapped correctly to the account. The usernamecache.json file is in the main folder for the server. The universalcoins.dat file is in the world/data folder.

**Comment by geekjam** [comment]
Thanks for your work! I had tested, is Essentials's problem

**Comment by notabadminer** [comment]
That's good news. I couldn't find anything that would cause the issue. I did add tab complete to the commands while I was going through the code so it wasn't all wasted time.
